Repository wangkanai/wangkanai, pull requests merged in 2025-05, with the labels that each got.

#1068 Add Error and Result primitives for domain operations
  .editorconfig
  Domain/src/AuditTrail.cs
  Domain/src/Primitives/Error.cs
  Domain/src/Primitives/Result.cs
  Domain/src/Properties/AssemblyInfo.cs
  Domain/tests/Primitives/ResultTests.cs
Labels: enhancement

#1070 Set SourceLink package reference for DEBUG configuration only
  Directory.Build.targets
Labels: dependencies, nuget

#1067 [Detection] Fix for Incorrect Browser reported for Edge and Firefox on iOS
  Detection/src/Services/BrowserService.cs
  Detection/tests/Services/BrowserServiceTests.cs
Labels: bug, fixed

#1073 Update version to 5.5.0 in Directory.Build.props
  System/Directory.Build.props
Labels: dependencies, nuget

#1075 Refactor code documentation for audit trail components
  Directory.Build.props
  Domain/Directory.Build.props
  Domain/README.md
  Domain/src/AuditTrail.cs
  Domain/src/TrailType.cs
Labels: enhancement

#1076 Reduce version prefixes across all projects.
  Analytics/Directory.Build.props
  Annotations/Directory.Build.props
  Blazor/Directory.Build.props
  Cryptography/Directory.Build.props
  Detection/Directory.Build.props
  EntityFramework/Directory.Build.props
  Extensions/Directory.Build.props
  Federation/Directory.Build.props
  Hosting/Directory.Build.props
  Identity/Directory.Build.props
  Markdown/Directory.Build.props
  Microservice/Directory.Build.props
  Microservice/README.md
  Mvc/Directory.Build.props
  Responsive/Directory.Build.props
  Security/Directory.Build.props
  Solver/Directory.Build.props
  System/Directory.Build.props
  Tabler/Directory.Build.props
  Testing/Directory.Build.props
  Tools/Directory.Build.props
  Validation/Directory.Build.props
  Webmaster/Directory.Build.props
  Webserver/Directory.Build.props
  build.ps1
  sign.ps1
Labels: enhancement, dependencies, nuget

#1077 Normalize project file formatting and update project references
  Analytics/src/Wangkanai.Analytics.csproj
  Analytics/tests/Wangkanai.Analytics.Tests.csproj
  Blazor/benchmark/Wangkanai.Blazor.Benchmark.csproj
  Blazor/src/Components/Wangkanai.Blazor.Components.csproj
  Blazor/src/Core/Wangkanai.Blazor.csproj
  Blazor/src/Web/Wangkanai.Blazor.Components.Web.csproj
  Blazor/tests/Wangkanai.Blazor.Tests.csproj
  Cryptography/benchmark/Wangkanai.Cryptography.Benchmark.csproj
  Cryptography/src/Wangkanai.Cryptography.csproj
  Cryptography/tests/Wangkanai.Cryptography.Tests.csproj
  Detection/benchmark/Wangkanai.Detection.Benchmark.csproj
  Detection/src/Wangkanai.Detection.csproj
  Domain/src/Wangkanai.Domain.csproj
  EntityFramework/src/Wangkanai.EntityFramework.csproj
  Extensions/Internal/src/Wangkanai.Extensions.Internal.csproj
  Federation/src/AspNetIdentity/Wangkanai.Federation.AspNetIdentity.csproj
  Federation/src/Domain/Wangkanai.Federation.Domain.csproj
  Federation/src/Federation/Wangkanai.Federation.csproj
  Hosting/src/Wangkanai.Hosting.csproj
  Identity/src/Wangkanai.Identity.csproj
  Markdown/src/Wangkanai.Markdown.csproj
  Microservice/src/Wangkanai.Microservice.csproj
  Mvc/src/Wangkanai.Mvc.csproj
  Nation/src/Wangkanai.Nation.csproj
  Responsive/src/Wangkanai.Responsive.csproj
  Responsive/tests/Wangkanai.Responsive.Tests.csproj
  Security/src/Core/Wangkanai.Security.Core.csproj
  Security/tests/Security/Wangkanai.Security.Tests.csproj
  Solver/src/Wangkanai.Solver.csproj
  Tabler/benchmark/Wangkanai.Tabler.Benchmark.csproj
  Tabler/src/Core/Wangkanai.Tabler.csproj
  Testing/src/Wangkanai.Testing.csproj
  Tools/MSBuild/src/Wangkanai.MSBuild.csproj
  Tools/Watcher/src/Wangkanai.Watcher.csproj
  Validation/src/Wangkanai.Validation.csproj
  Webmaster/src/Wangkanai.Webmaster.csproj
  Webmaster/tests/Wangkanai.Webmaster.Tests.csproj
  Webserver/src/Wangkanai.Webserver.csproj
Labels: enhancement, refactor

#1078 Update package versions in Directory.Packages.props
  Directory.Packages.props
Labels: enhancement, dependencies

#1079 Domain audit trail management system
  Domain/src/Primitives/ErrorCodes.cs
  Domain/src/Stores/AuditTrailStore.cs
  Domain/src/Stores/IAuditTrailStore.cs
  Domain/src/Stores/IQueryableAuditTrailStore.cs
  Domain/src/Usings.cs
Labels: enhancement, review, update

#1083 Update version prefix to 0.1.0
  Nation/Directory.Build.props
Labels: nuget

#1086 [Domain] Domain Events Handling
  Domain/src/Entity.cs
  Domain/src/Events/DomainEvent.cs
  Domain/src/Events/EventSuppressor.cs
  Domain/src/Events/GenericChangedEntry.cs
  Domain/src/Events/GuidDomainEvent.cs
  Domain/src/Events/ICancellableDomainEventHandler.cs
  Domain/src/Events/IDomainEvent.cs
  Domain/src/Events/IDomainEventDomainHandler.cs
  Domain/src/Events/IDomainEventPublisher.cs
  Domain/src/Events/IGuidDomainEvent.cs
  Domain/src/Interfaces/IAggregateRoot.cs
  Domain/src/Interfaces/IAuditable.cs
  Domain/src/Interfaces/ICreatedEntity.cs
  Domain/src/Interfaces/IDataEntity.cs
  Domain/src/Interfaces/IEntity.cs
  Domain/src/Interfaces/IFactory.cs
  Domain/src/Interfaces/IGuidAggregateRoot.cs
  Domain/src/Interfaces/IHasLanguage.cs
  Domain/src/Interfaces/IKeyByteEntity.cs
  Domain/src/Interfaces/IKeyGuidEntity.cs
  Domain/src/Interfaces/IKeyIntEntity.cs
  Domain/src/Interfaces/IKeyLongEntity.cs
  Domain/src/Interfaces/IKeyStringEntity.cs
  Domain/src/Interfaces/IRepository.cs
  Domain/src/Interfaces/IUnitOfWork.cs
  Domain/src/Interfaces/IUpdatedEntity.cs
  Domain/src/Interfaces/IUserAuditable.cs
  Domain/src/Interfaces/IValueObject.cs
  Domain/src/Messages/ICancellableDomainHandler.cs
  Domain/src/Messages/IDomainHandler.cs
  Domain/src/Messages/IDomainMessage.cs
  Domain/src/Stores/AuditTrailStore.cs
Labels: enhancement, refactor, unit-testing, update

#1087 [Domain] Audit Store for improved naming consistency across the domain
  Domain/src/Stores/AuditStore.cs
  Domain/src/Stores/IAuditStore.cs
  Domain/src/Stores/IAuditTrailStore.cs
  Domain/src/Stores/IQueryableAuditStore.cs
Labels: enhancement, refactor, unit-testing, reformat

#1088 [Domain] Audit Store implementation
  Domain/src/Configurations/AuditConfiguration.cs
  Domain/src/Extensions/AuditContextExtensions.cs
  Domain/src/Stores/AuditStore.cs
  Domain/src/Stores/IAuditStore.cs
  Domain/src/Stores/IQueryableAuditStore.cs
  Domain/tests/Configurations/AuditConfigurationTests.cs
  Domain/tests/Extensions/AuditContextExtensionsTests.cs
  Domain/tests/Stores/AuditStoreTests.cs
Labels: enhancement, unit-testing

#1090 Update VersionSuffix to Beta-5 in Domain build props
  Detection/Directory.Build.props
  Domain/Directory.Build.props
  Hosting/Directory.Build.props
  Responsive/Directory.Build.props
Labels: update

#1093 [Domain] Coverage unit tests for audit trail tracking entry
  Domain/src/AuditableEntity.cs
  Domain/src/Caching/CacheKey.cs
  Domain/src/Caching/ICacheKey.cs
  Domain/src/Common/PrimaryKeyResolvingMap.cs
  Domain/src/Common/ReflectionUtility.cs
  Domain/src/Configurations/AuditConfiguration.cs
  Domain/src/Entity.cs
  Domain/src/Events/EventSuppressor.cs
  Domain/src/Extensions/AuditContextExtensions.cs
  Domain/src/Extensions/EntityTypeBuilderExtensions.cs
  Domain/src/Interfaces/IUnitOfWork.cs
  Domain/src/KeyByteEntity.cs
  Domain/src/KeyGuidEntity.cs
  Domain/src/KeyIntEntity.cs
  Domain/src/KeyLongEntity.cs
  Domain/src/KeyStringEntity.cs
  Domain/src/Messages/ICancellableDomainHandler.cs
  Domain/src/NullCollection.cs
  Domain/src/Primitives/Error.cs
  Domain/src/Primitives/ErrorCodes.cs
  Domain/src/Primitives/Result.cs
  Domain/src/TrackingEntry.cs
  Domain/src/UserAuditableEntity.cs
  Domain/src/ValueObject.cs
  Domain/tests/Models/AuditEntity.cs
  Domain/tests/Models/CreatedEntity.cs
  Domain/tests/Models/GuidEntity.cs
  Domain/tests/Models/IntEntity.cs
  Domain/tests/Models/UpdatedEntity.cs
  Domain/tests/TrackingEntryTests.cs
  Domain/tests/ValueObjectTests.cs
Labels: enhancement, unit-testing
